### ISSUE TITLE
Purpose of use extensions?

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/AuditEvent#1]
Mulig vi har diskutert dette tidligere, men hvorfor benyttes ikke elementet purposeOfEvent istedenfor å legge den samme (?) informasjonen i en extension? 

Det virker som begrunnelsen bare er at dere trenger en assigner element på disse kodene og dere ikke har funnet en måte å legge det inn i purposeOfEvent. Det er uklart, basert på definisjonen i IG hva denne strukturen brukes til, hvorfor og hvordan informasjonen skal tolkes når man sender og mottar. Det burde nok vært bedre dokumentasjon av selve utvidelsen?

**Comment by troelde** [comment]
> Mulig vi har diskutert dette tidligere, men hvorfor benyttes ikke elementet purposeOfEvent istedenfor å legge den samme (?) informasjonen i en extension?

Ja, det blir nok riktigere å benytte `purposeOfEvent `som i R5 heter [`authorization`](https://www.hl7.org/fhir/auditevent-definitions.html#AuditEvent.authorization).

Hvorvidt assigner skal være med er en generell problemstilling som gjelder alle kodeverksattributter i fra felles tillitsrammeverk: https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md.  Det er jo litt rart at ikke assigner eller authority kunne være en del av FHIR sin [Coding element](https://www.hl7.org/fhir/datatypes.html#Coding).
