### ISSUE TITLE
Helsepersonell med et nasjonalt identitetsnummer er påkrevd informasjon

### ISSUE THREAD

**Issue by eirikbroen** [HL7Norway/AuditEvent#4]
Helsepersonell (practitioner) er et påkrevd element i helsepersonellattesten tilhørende Tillitsrammeverket. Videre er helsepersonellets identitet et påkrevd attributt [ref](https://github.com/NorskHelsenett/Tillitsrammeverk/blob/main/specs/informasjons_og_datamodell.md#431-identifier-helsepersonellet-som-fysisk-person). 

Dette er i tråd med bestemmelsene om hva som _skal_ logges ved innsyn i helseopplysninger som beskrevet i Normen [ref](https://www.ehelse.no/normen/normen-dokumenter/logging-og-innsyn-i-logg-faktaark-15#3.hva-som-skal-logges-nbsp)

Foreslår derfor at profil for [AuditEvent](https://hl7norway.github.io/AuditEvent/currentbuild/StructureDefinition-no-domain-Trustframework-Auditevent.html) bør endres slik at AuditEvent.agent har en kardinalitet på 1..1 og er en referanse til [no-doc-Trustframework-Practitioner](https://hl7norway.github.io/AuditEvent/currentbuild/StructureDefinition-no-doc-Trustframework-Practitioner.html) 

Videre foreslår jeg at denne profilen av Practitioner bør sette kardinalitet på Identity slice til 1..* ikke 0..* som i no-basis-practitioner. Det ikke noe krav til at helsepersonell skal være registrert i HPR, kan derfor ha 0..1 på hpr-slice. Enten FNR eller DNR må være satt, men vet ikke hvordan man utrykker choice i FHIR struktur. Ser ikke helt hvorfor vi må introdusere et ekstra Identity attributt, hvorfor ikke bare utvide slices fra basisprofil og legge til assigner med statisk verdi for FNR/DNR og HPR?

Min erfaring med profilering av HL7 FHIR ressurser er begrenset så ber på forhånd om unnskyldning for både feil begrepsbruk og mindre gjennomtenkte forslag.

**Comment by thomiz** [comment]
Interessant diskusjon spesielt om identiteten til practitioner skal være påkrevd i [no-doc-Trustframework-Practitioner](https://hl7norway.github.io/AuditEvent/currentbuild/StructureDefinition-no-doc-Trustframework-Practitioner.html). Jeg mistenker at hovedgrunnen til at det ble slik som det er idag var at vi først tenkte dette skulle være basisprofiler og der stiller vi ingen slike krav, og mappingen til tillitsrammeverket (helsepersonellets attest) er ren informativ mapping informasjon. 

Vi har da to muligheter. Hvis vi holder fast på den modellen er det riktig at det blir dokumentasjon og dermed frivillig med identiteten til Practitioner. Hvis vi derimot sier at reglene i helsepersonellets attest skal gjenspeiles tydelig i profilen noe [introduksjonen](https://hl7norway.github.io/AuditEvent/currentbuild/index.html#introduction) åpner for så bør vi gjør om på dette og gjenspeile krav til informasjonsinnhold mer nøyaktig fra spesifikasjonen for helsepersonellets attest.

Jeg ser ingen enkel måte å kreve FNR eller DNR samtidig som man har opsjon for HPR, uten å definere dette som en invariant. Invarianten gjør det mulig å validere på dette, men det er ikke spesielt enkelt å lese slike krav i dokumentasjonen...

Diskutere i TSK @oyvindaa1 ?

**Comment by oyvindaa1** [comment]
Yep, setter det på agenda på neste møte (ikke fredag 11/10).

**Comment by troelde** [comment]
Utover endring hvor obligatoriske + endring fra no-doc- til no-domain på flere profiler, så ble det vi kanskje enig om at forretningsregelen "FNR eller DNR samtidig som man har opsjon for HPR" ikke tas med pga. kompleksitet?

**Comment by oaassv** [comment]
Jepp,kombinasjonen der blir litt komplisert. 
øyvind
    På onsdag 6. november 2024 kl. 13:20:44 CET skrev Trond Elde ***@***.***> følgende:  
 
 


Utover endring hvor obligatoriske + endring fra no-doc- til no-domain på flere profiler, så ble det vi kanskje enig om at forretningsregelen "FNR eller DNR samtidig som man har opsjon for HPR" ikke tas med pga. kompleksitet?

**Comment by troelde** [comment]
Så denne først nå etter e-post ble sendt. Lukker denne
